version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - mongodb:/data/db

  mongo-seed:
    image: mongo:5.0
    links:
      - mongodb
    volumes:
      - ./init-mongodb/seed:/mongo-seed
    command: "./mongo-seed/import.sh"

volumes:
  mongodb:
